networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:  
  cdr-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-marketplace-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-config/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${MARKETPLACE_SERVICE_PORT}:${MARKETPLACE_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
    restart: always